name: shield
description: "Shield"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
